/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek_mini_cafe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static projek_mini_cafe.konek.getConnection;

public class Master_Data extends javax.swing.JFrame {

    konek db = new konek();
    Connection conn = getConnection();
    String sumtotal = null;
    String cari = ""; 
    String total1 = "";
    String total2 = "";
    String Sum = null;
    int hargatotal;
    int k = 0;
    /**
     * Creates new form Admi_transaksi
     */
    public Master_Data() {
        initComponents();
        setLocationRelativeTo(null);
        tableTransaksi(TbTransaksi);        
        btncek.setVisible(false);
        tblist.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbTransaksi = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txsearch = new javax.swing.JTextField();
        SearchTransaksi = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txidpeg = new javax.swing.JTextField();
        txidtrans = new javax.swing.JTextField();
        txidmakanan = new javax.swing.JTextField();
        txidminuman = new javax.swing.JTextField();
        txdate = new javax.swing.JTextField();
        txjummakanan = new javax.swing.JTextField();
        txjumminuman = new javax.swing.JTextField();
        txtotalharga = new javax.swing.JTextField();
        txpembayaran = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txkembalian = new javax.swing.JTextField();
        idmk = new javax.swing.JTextField();
        idmn = new javax.swing.JTextField();
        pegname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblist = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        setid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        setgl = new javax.swing.JLabel();
        btncek = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        areamakan = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaminum = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin | Data Master");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N

        TbTransaksi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        TbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_pegawai", "id_transaksi", "id_makanan", "id_minuman", "tgl_transaksi", "jumlah_makanan", "jumlah_minuman", "total_harga", "pembayaran", "kembalian", "Laporan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbTransaksi);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("No. Transaksi");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Pegawai");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Makanan");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Minuman");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton5.setText("C");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txsearch.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        SearchTransaksi.setBackground(new java.awt.Color(204, 255, 204));
        SearchTransaksi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        SearchTransaksi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cari berdasarkan...", "id_pegawai", "id_transaksi", "id_makanan", "id_minuman" }));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Jumlah makanan");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah Minuman");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Total Harga");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Pembayaran");

        txidpeg.setEditable(false);
        txidpeg.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txidtrans.setEditable(false);
        txidtrans.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txidmakanan.setEditable(false);
        txidmakanan.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txidminuman.setEditable(false);
        txidminuman.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txdate.setEditable(false);
        txdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txdate.setText("Tgl Transaksi");

        txjummakanan.setEditable(false);
        txjummakanan.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txjumminuman.setEditable(false);
        txjumminuman.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txtotalharga.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txpembayaran.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCari.setText("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Kembalian");

        txkembalian.setEditable(false);
        txkembalian.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        idmk.setEditable(false);
        idmk.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        idmn.setEditable(false);
        idmn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        pegname.setEditable(false);
        pegname.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        tblist.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tblist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Makanan", "Minuman"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblist);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("ID :");

        setid.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setText("Tanggal : ");

        setgl.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        btncek.setBackground(new java.awt.Color(255, 255, 255));
        btncek.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btncek.setText("CEK");
        btncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekActionPerformed(evt);
            }
        });

        areamakan.setEditable(false);
        areamakan.setColumns(20);
        areamakan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        areamakan.setRows(5);
        jScrollPane4.setViewportView(areamakan);

        areaminum.setEditable(false);
        areaminum.setColumns(20);
        areaminum.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        areaminum.setRows(5);
        jScrollPane5.setViewportView(areaminum);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("~ ~ ~ Makanan ~ ~ ~");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("~ ~ ~ Minuman ~ ~ ~");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 75)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("~ Mini Cafe ~");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(1260, 1260, 1260))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SearchTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(pegname, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txidpeg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txidmakanan, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txidminuman, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(idmk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idmn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txjummakanan, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txjumminuman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton6))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(txdate))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(setgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncek, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pegname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txidpeg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txidmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idmk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txidminuman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idmn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txjummakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txjumminuman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(setgl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncek, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5)))))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbTransaksiMouseClicked
        // TODO add your handling code here:
        String makan = "";
        String minum = "";
        String pegpeg = "";
        String a = String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 2));
        String b = String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 3));
        String c = String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 0));
        try{
            String sql = "Select nama_pegawai FROM pegawai WHERE id_pegawai = " + c;
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while(rset.next()){
                pegpeg = rset.getString(1);
            }
        }catch(Exception ex){  
        }
        try{
            String sql = "Select nama_makanan FROM makanan WHERE id_makanan = " + a;
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while(rset.next()){
                makan = rset.getString(1);
            }
        }catch(Exception ex){  
        }
        try{
            String sql = "Select nama_minuman FROM minuman WHERE id_minuman = " + b;
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while(rset.next()){
                minum = rset.getString(1);
            }
        }catch(Exception ex){  
        }
        
        pegname.setText(pegpeg);
        txidpeg.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 0)));
        txidtrans.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 1)));
        txidmakanan.setText(makan);
        idmk.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 2)));
        txidminuman.setText(minum);
        idmn.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 3)));
        txdate.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 4)));
        txjummakanan.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 5)));
        txjumminuman.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 6)));
        txtotalharga.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 7)));
        txpembayaran.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 8)));
        txkembalian.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 9)));
        setid.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 10)));
        setgl.setText(String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 4)));
        
        tableList(tblist, String.valueOf(TbTransaksi.getValueAt(TbTransaksi.getSelectedRow(), 10)));
        btncek.setVisible(true);
        tblist.setVisible(true);
        
        areamakan.setText("");
        areaminum.setText("");
    }//GEN-LAST:event_TbTransaksiMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new admin_control().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TransaksiClear();
        DefaultTableModel m = (DefaultTableModel)tblist.getModel();
        for(int x = m.getRowCount() - 1; x >= 0; x--){
           m.removeRow(x);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    public void TransaksiClear(){
        txidpeg.setText("");
        pegname.setText("");
        txidtrans.setText("");
        txidmakanan.setText("");
        idmk.setText("");
        txidminuman.setText("");
        idmn.setText("");
        txdate.setText("Tgl Transaksi");
        txjummakanan.setText("");
        txjumminuman.setText("");
        txtotalharga.setText("");
        txpembayaran.setText("");
        txkembalian.setText("");
        txsearch.setText("");
        setid.setText("");
        setgl.setText("");
        areamakan.setText("");
        areaminum.setText("");
        tableTransaksi(TbTransaksi);
    }
    
    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari = SearchTransaksi.getSelectedItem().toString();
        if(cari.equals("id_pegawai")){
            searchTrans1(TbTransaksi);
        }else if(cari.equals("id_transaksi")){
            searchTrans2(TbTransaksi);
        }else if(cari.equals("id_makanan")){
            searchTrans3(TbTransaksi);
        }else if(cari.equals("id_minuman")){
            searchTrans4(TbTransaksi);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int kembali = 0;
        kembali = Integer.parseInt(txpembayaran.getText()) - Integer.parseInt(txtotalharga.getText());
        
        try {
            String sql = "UPDATE transaksi SET total_harga = " + txtotalharga.getText() 
                    + ", jumlah_makanan = " + txjummakanan.getText() 
                    + ", jumlah_minuman = " + txjumminuman.getText()
                    + ", kembalian = " + kembali 
                    + ", pembayaran = " + txpembayaran.getText()
                    + " WHERE id_transaksi = " + txidtrans.getText();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            TransaksiClear();
            tableTransaksi(TbTransaksi);
            JOptionPane.showMessageDialog(null, "Data Berhasil di update!!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int yakingak = JOptionPane.showConfirmDialog(null, "Hapus Gak??", "WARNING!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(yakingak == 0){
            db.putData("DELETE FROM transaksi WHERE id_transaksi = " + txidtrans.getText());

            TransaksiClear();
            tableTransaksi(TbTransaksi);
            JOptionPane.showMessageDialog(null, "Data Deleted");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mode = (DefaultTableModel)tblist.getModel();
        int no = mode.getRowCount();
        String[] a = new String[no];
        String aa = "";
        String bb = "";
        
        Object[] list = new Object[2];
        for(int i = 0; i < mode.getRowCount();i++){
            list[0] = mode.getValueAt(i, 0);
            try{
                String sql = "Select nama_makanan FROM makanan WHERE id_makanan = " + list[0];
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while(rset.next()){
                    aa = rset.getString(1);
                    areamakan.append(" ~> " + aa + "\n");
                }
            }catch(Exception ex){  
            }
        }
        for(int i = 0; i < mode.getRowCount();i++){
            list[1] = mode.getValueAt(i, 1);
            try{
                String sql = "Select nama_minuman FROM minuman WHERE id_minuman = " + list[1];
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while(rset.next()){
                    bb = rset.getString(1);
                    areaminum.append(" ~> " + bb + "\n");
                }
            }catch(Exception ex){  
            }
        }

        btncek.setVisible(false);
    }//GEN-LAST:event_btncekActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SearchTransaksi;
    private javax.swing.JTable TbTransaksi;
    private javax.swing.JTextArea areamakan;
    private javax.swing.JTextArea areaminum;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btncek;
    private javax.swing.JTextField idmk;
    private javax.swing.JTextField idmn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField pegname;
    private javax.swing.JLabel setgl;
    private javax.swing.JLabel setid;
    private javax.swing.JTable tblist;
    private javax.swing.JTextField txdate;
    private javax.swing.JTextField txidmakanan;
    private javax.swing.JTextField txidminuman;
    private javax.swing.JTextField txidpeg;
    private javax.swing.JTextField txidtrans;
    private javax.swing.JTextField txjummakanan;
    private javax.swing.JTextField txjumminuman;
    private javax.swing.JTextField txkembalian;
    private javax.swing.JTextField txpembayaran;
    private javax.swing.JTextField txsearch;
    private javax.swing.JTextField txtotalharga;
    // End of variables declaration//GEN-END:variables
    private void tableTransaksi(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi order by id_transaksi");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                v.add(rset.getString(10));
                v.add(rset.getString(11));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    private void tableList(JTable jt, String aid) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT id_makanan, id_minuman FROM transaksi WHERE id_lap = " + aid + " order by id_transaksi");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    private void searchTrans1(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_pegawai LIKE '%" + txsearch.getText()+ "%' ");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                v.add(rset.getString(10));
                v.add(rset.getString(11));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    private void searchTrans2(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_transaksi LIKE '%" + txsearch.getText()+ "%' ");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                v.add(rset.getString(10));
                v.add(rset.getString(11));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    private void searchTrans3(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_makanan LIKE '%" + txsearch.getText()+ "%' ");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                v.add(rset.getString(10));
                v.add(rset.getString(11));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    private void searchTrans4(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_minuman LIKE '%" + txsearch.getText()+ "%' ");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                v.add(rset.getString(10));      
                v.add(rset.getString(11));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    
    


}
