/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projek_mini_cafe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static projek_mini_cafe.konek.getConnection;

public class pesanan extends javax.swing.JFrame {

    konek db = new konek();
    Connection conn = getConnection();
    private int id;
    public String mk = "";
    public String mn = "";
    String hrgm = "";
    String hrgmi = "";
    int total=0;
    String juml = "";
    /** Creates new form menu */
    public pesanan(int id) {
        initComponents();
        setLocationRelativeTo(null);
        tablemenuMakan(tbmenumakan);
        tablemenuMinum(tbmenuminum);
        this.id = id;
        txaidi.setText(""+this.id);
        txaidi.setVisible(false);
        txmakan.setVisible(false);        
        txminum.setVisible(false);
        
        pemakHiden();
        tamak.setVisible(false);
        Emak.setVisible(false);
        delmak.setVisible(false);
        
        peminHiden();
        tamin.setVisible(false);
        Emin.setVisible(false);
        delmin.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmenumakan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbmenuminum = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txaidi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txjumlahmakan = new javax.swing.JTextField();
        lbmakan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbpesanmakan = new javax.swing.JTable();
        tamak = new javax.swing.JButton();
        txmakan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Emak = new javax.swing.JButton();
        delmak = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txjumlahminum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbminum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbpesanminum = new javax.swing.JTable();
        txminum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tamin = new javax.swing.JButton();
        delmin = new javax.swing.JButton();
        Emin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 18))); // NOI18N

        tbmenumakan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tbmenumakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Makanan", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmenumakan.setGridColor(new java.awt.Color(255, 255, 255));
        tbmenumakan.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbmenumakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmenumakanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbmenumakanMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbmenumakan);

        tbmenuminum.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tbmenuminum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Minuman", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmenuminum.setGridColor(new java.awt.Color(255, 255, 255));
        tbmenuminum.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbmenuminum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmenuminumMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbmenuminum);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-- Minuman --");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-- Makanan --");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txaidi.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txaidi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText(">> Makanan - - - - - - -");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jumlah");

        txjumlahmakan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txjumlahmakan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txjumlahmakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txjumlahmakanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txjumlahmakanMouseEntered(evt);
            }
        });
        txjumlahmakan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txjumlahmakanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txjumlahmakanKeyReleased(evt);
            }
        });

        lbmakan.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N

        tbpesanmakan.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tbpesanmakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Makanan", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpesanmakan.setGridColor(new java.awt.Color(255, 255, 255));
        tbpesanmakan.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbpesanmakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpesanmakanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbpesanmakan);

        tamak.setBackground(new java.awt.Color(255, 255, 255));
        tamak.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tamak.setText("Tambah");
        tamak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamakActionPerformed(evt);
            }
        });

        txmakan.setEditable(false);
        txmakan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~");

        Emak.setBackground(new java.awt.Color(255, 255, 255));
        Emak.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Emak.setText("Edit");
        Emak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmakActionPerformed(evt);
            }
        });

        delmak.setBackground(new java.awt.Color(255, 255, 255));
        delmak.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        delmak.setText("Delete");
        delmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delmakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txmakan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbmakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txjumlahmakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tamak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Emak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delmak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txmakan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txjumlahmakan, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lbmakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delmak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N

        txjumlahminum.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txjumlahminum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txjumlahminum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txjumlahminumMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText(">> Minuman - - - - - - -");

        lbminum.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jumlah");

        tbpesanminum.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tbpesanminum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Minuman", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpesanminum.setGridColor(new java.awt.Color(255, 255, 255));
        tbpesanminum.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbpesanminum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpesanminumMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbpesanminum);

        txminum.setEditable(false);
        txminum.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~");

        tamin.setBackground(new java.awt.Color(255, 255, 255));
        tamin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tamin.setText("Tambah");
        tamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taminActionPerformed(evt);
            }
        });

        delmin.setBackground(new java.awt.Color(255, 255, 255));
        delmin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        delmin.setText("Delete");
        delmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delminActionPerformed(evt);
            }
        });

        Emin.setBackground(new java.awt.Color(255, 255, 255));
        Emin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Emin.setText("Edit");
        Emin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(6, 6, 6)
                                        .addComponent(txminum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbminum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txjumlahminum, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tamin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Emin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txminum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbminum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txjumlahminum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Emin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tamin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("Pesan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txaidi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txaidi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        String npeg = "";
        try{
            String sql = "Select nama_pegawai FROM pegawai WHERE id_pegawai = " + txaidi.getText();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while(rset.next()){
                npeg = rset.getString(1);
            }
        }catch(Exception ex){  
        }
        
        DefaultTableModel modmakan1 = (DefaultTableModel)tbpesanmakan.getModel();
        DefaultTableModel modminum1 = (DefaultTableModel)tbpesanminum.getModel();
        if(modmakan1.getRowCount() != modminum1.getRowCount()){
            JOptionPane.showMessageDialog(null, "Pilih Makanan / Minuman", "", JOptionPane.WARNING_MESSAGE);
        }else{
        transaksi tr = new transaksi(this.id);
        transaksi.nmpega.setText(npeg);
        transaksi.date.setText(String.valueOf(new java.sql.Date(System.currentTimeMillis())));
        transaksi.totalharga.setText(Integer.toString(tot() + tot2()));
        
        
        Object[] rowmak = new Object[4];
        DefaultTableModel modmakan2 = (DefaultTableModel)transaksi.tbpesanmakan.getModel();
        for(int i = 0; i < modmakan1.getRowCount();i++){
            rowmak[0] = modmakan1.getValueAt(i, 0);  
            rowmak[1] = modmakan1.getValueAt(i, 1);
            rowmak[2] = modmakan1.getValueAt(i, 2);
            modmakan2.addRow(rowmak);
        }
        
        
        Object[] rowmin = new Object[4];
        DefaultTableModel modminum2 = (DefaultTableModel)transaksi.tbpesanminum.getModel();
        for(int i = 0; i < modminum1.getRowCount();i++){
            rowmin[0] = modminum1.getValueAt(i, 0);  
            rowmin[1] = modminum1.getValueAt(i, 1);
            rowmin[2] = modminum1.getValueAt(i, 2);
            modminum2.addRow(rowmin);
        }
               
        tr.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public int tot(){
        int hargaCount = tbpesanmakan.getRowCount();
        int sum = 0;
        for(int u = 0; u < hargaCount; u++){
            sum = sum+Integer.parseInt(tbpesanmakan.getValueAt(u, 3).toString());
        }
        return sum;
    }
    public int tot2(){
        int hargaCount2 = tbpesanminum.getRowCount();
        int sum2 = 0;
        for(int u = 0; u < hargaCount2; u++){
            sum2 = sum2+Integer.parseInt(tbpesanminum.getValueAt(u, 3).toString());
        }
        return sum2;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txjumlahmakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txjumlahmakanMouseClicked
        // TODO add your handling code here:
        txjumlahmakan.setBackground(Color.WHITE);
    }//GEN-LAST:event_txjumlahmakanMouseClicked

    private void txjumlahminumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txjumlahminumMouseClicked
        // TODO add your handling code here:
        txjumlahminum.setBackground(Color.WHITE);
    }//GEN-LAST:event_txjumlahminumMouseClicked

    private void tbmenumakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmenumakanMouseClicked
        // TODO add your handling code here:
        String nomakan = "";
        
        nomakan = String.valueOf(tbmenumakan.getValueAt(tbmenumakan.getSelectedRow(), 0));
        txmakan.setText(nomakan);
        try{
            String sqlplus = "SELECT * FROM makanan WHERE id_makanan = " + nomakan;
            PreparedStatement pset = conn.prepareStatement(sqlplus);
            ResultSet rset = pset.executeQuery(sqlplus);
            while (rset.next()){
                mk = rset.getString(3);
                hrgm = rset.getString(4);
            }
        }catch(Exception ee){
            JOptionPane.showMessageDialog(null, ee.getMessage());
        }
        lbmakan.setText(mk);
        pemakTampil();
        tamak.setVisible(true);
    }//GEN-LAST:event_tbmenumakanMouseClicked

    
    private void tbmenuminumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmenuminumMouseClicked
        // TODO add your handling code here:
        String nominum = "";
        nominum = String.valueOf(tbmenuminum.getValueAt(tbmenuminum.getSelectedRow(), 0));
        txminum.setText(nominum);
        try{
            String sqlplus = "SELECT * FROM minuman WHERE id_minuman = " + nominum;
            PreparedStatement pset = conn.prepareStatement(sqlplus);
            ResultSet rset = pset.executeQuery(sqlplus);
            while (rset.next()){
                mn = rset.getString(2);
                hrgmi = rset.getString(3);
            }
        }catch(Exception ee){
            JOptionPane.showMessageDialog(null, ee.getMessage());
        }
        lbminum.setText(mn);
        peminTampil();
        tamin.setVisible(true);
    }//GEN-LAST:event_tbmenuminumMouseClicked

    private void tamakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamakActionPerformed
        // TODO add your handling code here:
        boolean ceknul = false;
        if(lbmakan.getText().equals("")){
            ceknul = true;
            JOptionPane.showMessageDialog(null, "Pilih Menu Makanan!!","WARNING!!", JOptionPane.ERROR_MESSAGE);
        }
        if(txjumlahmakan.getText().trim().equals("")){
            ceknul = true;
            txjumlahmakan.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Input Jumlah pemesanan !!","WARNING!!", JOptionPane.ERROR_MESSAGE);
        }
        
        int totmm = Integer.parseInt(hrgm) * Integer.parseInt(txjumlahmakan.getText());
        
        if(!ceknul){
            String li = String.valueOf(tbmenumakan.getValueAt(tbmenumakan.getSelectedRow(), 1));  

            DefaultTableModel mod = (DefaultTableModel)tbpesanmakan.getModel();
            mod.addRow(new Object[]{
                txmakan.getText(),li, txjumlahmakan.getText(), totmm
            });
            pemakHiden();
            tablemenuMakan(tbmenumakan);
            lbmakan.setText("");
            txjumlahmakan.setText("");
            tamak.setVisible(false);
        }
    }//GEN-LAST:event_tamakActionPerformed

    private void tbpesanmakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpesanmakanMouseClicked
        // TODO add your handling code here:
        txmakan.setText(String.valueOf(tbpesanmakan.getValueAt(tbpesanmakan.getSelectedRow(), 0)));
        lbmakan.setText(String.valueOf(tbpesanmakan.getValueAt(tbpesanmakan.getSelectedRow(), 1)));
        txjumlahmakan.setText(String.valueOf(tbpesanmakan.getValueAt(tbpesanmakan.getSelectedRow(), 2)));
        pemakTampil();
        tamak.setVisible(false);
        Emak.setVisible(true);
        delmak.setVisible(true);
    }//GEN-LAST:event_tbpesanmakanMouseClicked

    private void taminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taminActionPerformed
        // TODO add your handling code here:
        boolean ceknul = false;
        if(lbminum.getText().equals("")){
            ceknul = true;
            JOptionPane.showMessageDialog(null, "Pilih Menu Minuman!!","WARNING!!", JOptionPane.ERROR_MESSAGE);
        }
        if(txjumlahminum.getText().trim().equals("")){
            ceknul = true;
            txjumlahminum.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Input Jumlah pemesanan !!","WARNING!!", JOptionPane.ERROR_MESSAGE);
        }
        
        int totmm = Integer.parseInt(hrgmi) * Integer.parseInt(txjumlahminum.getText());
        
        if(!ceknul){
            String li = String.valueOf(tbmenuminum.getValueAt(tbmenuminum.getSelectedRow(), 1));  

            DefaultTableModel mod = (DefaultTableModel)tbpesanminum.getModel();
            mod.addRow(new Object[]{
                txminum.getText(),li, txjumlahminum.getText(), totmm
            });
            peminHiden();
            tablemenuMinum(tbmenuminum);
            lbminum.setText("");
            txjumlahminum.setText("");
            tamin.setVisible(false);
        }
    }//GEN-LAST:event_taminActionPerformed

    private void EmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmakActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modmak = (DefaultTableModel) tbpesanmakan.getModel();
        int i = tbpesanmakan.getSelectedRow();
        if(i >=0 ){
            modmak.setValueAt(txmakan.getText(), i, 0);
            modmak.setValueAt(lbmakan.getText(), i, 1);
            modmak.setValueAt(txjumlahmakan.getText(), i, 2);
            pemakHiden();
            lbmakan.setText("");
            txjumlahmakan.setText("");
            Emak.setVisible(false);
            delmak.setVisible(false);
        }else{
            System.err.println("Edit gagal!!");
        }
    }//GEN-LAST:event_EmakActionPerformed

    private void delmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delmakActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modmak = (DefaultTableModel) tbpesanmakan.getModel();
        int i = tbpesanmakan.getSelectedRow();
        if(i>=0){
            modmak.removeRow(i);
            pemakHiden();
            lbmakan.setText("");
            txjumlahmakan.setText("");
            Emak.setVisible(false);
            delmak.setVisible(false);
        }else{
            System.err.println("Gagal Hapus");
        }
    }//GEN-LAST:event_delmakActionPerformed

    private void delminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delminActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modmin = (DefaultTableModel) tbpesanminum.getModel();
        int i = tbpesanminum.getSelectedRow();
        if(i>=0){
            modmin.removeRow(i);
            peminHiden();
            lbminum.setText("");
            txjumlahminum.setText("");
            Emin.setVisible(false);
            delmin.setVisible(false);
        }else{
            System.err.println("Gagal Hapus");
        }
    }//GEN-LAST:event_delminActionPerformed

    private void EminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EminActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modmin = (DefaultTableModel) tbpesanminum.getModel();
        int i = tbpesanminum.getSelectedRow();
        if(i >=0 ){
            modmin.setValueAt(txminum.getText(), i, 0);
            modmin.setValueAt(lbminum.getText(), i, 1);
            modmin.setValueAt(txjumlahminum.getText(), i, 2);
            peminHiden();
            lbminum.setText("");
            txjumlahminum.setText("");
            Emin.setVisible(false);
            delmin.setVisible(false);
        }else{
            System.err.println("Edit gagal!!");
        }
    }//GEN-LAST:event_EminActionPerformed

    private void tbpesanminumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpesanminumMouseClicked
        // TODO add your handling code here:
        txminum.setText(String.valueOf(tbpesanminum.getValueAt(tbpesanminum.getSelectedRow(), 0)));
        lbminum.setText(String.valueOf(tbpesanminum.getValueAt(tbpesanminum.getSelectedRow(), 1)));
        txjumlahminum.setText(String.valueOf(tbpesanminum.getValueAt(tbpesanminum.getSelectedRow(), 2)));
        peminTampil();
        tamin.setVisible(false);
        Emin.setVisible(true);
        delmin.setVisible(true);
    }//GEN-LAST:event_tbpesanminumMouseClicked

    private void tbmenumakanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmenumakanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbmenumakanMouseEntered

    private void txjumlahmakanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txjumlahmakanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txjumlahmakanMouseEntered

    private void txjumlahmakanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txjumlahmakanKeyPressed
        // TODO add your handling code here:       
    }//GEN-LAST:event_txjumlahmakanKeyPressed

    private void txjumlahmakanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txjumlahmakanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txjumlahmakanKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new pesanan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Emak;
    private javax.swing.JButton Emin;
    private javax.swing.JButton delmak;
    private javax.swing.JButton delmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbmakan;
    private javax.swing.JLabel lbminum;
    private javax.swing.JButton tamak;
    private javax.swing.JButton tamin;
    private javax.swing.JTable tbmenumakan;
    private javax.swing.JTable tbmenuminum;
    private javax.swing.JTable tbpesanmakan;
    private javax.swing.JTable tbpesanminum;
    private javax.swing.JLabel txaidi;
    private javax.swing.JTextField txjumlahmakan;
    private javax.swing.JTextField txjumlahminum;
    private javax.swing.JTextField txmakan;
    private javax.swing.JTextField txminum;
    // End of variables declaration//GEN-END:variables
    private void tablemenuMakan(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM makanan order by id_makanan");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(3));
                v.add(rset.getString(5));

                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    
    private void tablemenuMinum(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM minuman order by id_minuman");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));    
                v.add(rset.getString(4));

                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    
    public void pemakHiden(){
        lbmakan.setVisible(false);
        txjumlahmakan.setVisible(false);
        jLabel4.setVisible(false);
    }
    public void pemakTampil(){
        lbmakan.setVisible(true);
        txjumlahmakan.setVisible(true);
        jLabel4.setVisible(true);
    }
    
    public void peminHiden(){
        lbminum.setVisible(false);
        txjumlahminum.setVisible(false);
        jLabel7.setVisible(false);
    }
    public void peminTampil(){
        lbminum.setVisible(true);
        txjumlahminum.setVisible(true);
        jLabel7.setVisible(true);
    }
    
    
    
    
    
    
    
}
